services:
  - type: web
    name: latar-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://acqu1red.github.io/latar/
    healthCheckPath: /healthz
