# Timeweb конфигурация для деплоя
name: latar-backend
type: nodejs
version: 22

# Настройки приложения
build:
  command: "npm install --production"
  working_directory: "."

# Переменные окружения
environment:
  NODE_ENV: production
  PORT: 3001
  SCRIBBLE_DIFFUSION_API_KEY: "YOUR_SCRIBBLE_DIFFUSION_API_KEY_HERE"

# Настройки сервера
server:
  port: 3001
  health_check: "/healthz"
  start_command: "node --max-old-space-size=4096 server.mjs"

# Настройки ресурсов
resources:
  memory: 1024MB
  cpu: 1.0

# Настройки сети
network:
  allow_internet: true
  allow_internal: true
