# Timeweb конфигурация для деплоя
name: latar-backend
type: nodejs
version: 20

# Настройки приложения
build:
  command: "cd backend && npm install --only=production"
  working_directory: "backend"

# Переменные окружения
environment:
  NODE_ENV: production
  PORT: 3001
  SCRIBBLE_DIFFUSION_API_KEY: "YOUR_SCRIBBLE_DIFFUSION_API_KEY_HERE"

# Настройки сервера
server:
  port: 3001
  health_check: "/healthz"

# Настройки ресурсов
resources:
  memory: 512MB
  cpu: 0.5

# Настройки сети
network:
  allow_internet: true
  allow_internal: true
