# Koyeb конфигурация для деплоя backend
name: latar-backend
services:
  - name: latar-backend
    source:
      type: git
      git:
        repository: https://github.com/acqu1red/latar
        branch: main
        working_directory: backend
    ports:
      - port: 3001
        protocol: http
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3001"
    build:
      type: dockerfile
      dockerfile_path: backend/Dockerfile
    run:
      command: ["node", "--max-old-space-size=4096", "server.mjs"]
      args: []
    healthcheck:
      http:
        path: /healthz
        port: 3001
        initial_delay: 30
        interval: 10
        timeout: 5
        unhealthy_threshold: 3
        healthy_threshold: 2