services:
  - type: web
    name: latar-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /healthz
    autoDeploy: true
    branch: main
    rootDir: backend
