name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**', '.github/workflows/**' ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Clear cache
        run: |
          cd frontend
          rm -rf .next out node_modules/.cache

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build
        run: |
          cd frontend
          echo "Building in directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          npm run build
          echo "Build completed. Checking output:"
          ls -la

      - name: List build output
        run: |
          cd frontend
          echo "Contents of frontend directory:"
          ls -la
          echo "Contents of out directory:"
          ls -la out/ || echo "out directory not found"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Verify output directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of frontend directory:"
          ls -la frontend/
          echo "Contents of frontend/out directory:"
          ls -la frontend/out/ || echo "frontend/out directory not found"
          echo "Checking if frontend/out exists:"
          test -d frontend/out && echo "frontend/out exists" || echo "frontend/out does not exist"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/out
        continue-on-error: false

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
